server:
  port: 8080

spring:
  application:
    name: mcp

  datasource:
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  ai:
    openai:
      api-key:
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.3-70b-versatile

cashfree:
  client-id:
  client-secret:
  base-url: https://sandbox.cashfree.com